name: dev_compiler
version: 0.2.0-unofficial.2017042201
description: >
  Experimental Dart to JavaScript compiler designed to create idiomatic,
  readable JavaScript output.

author: Dart Dev Compiler team <dev-compiler@dartlang.org>
homepage: https://github.com/dart-lang/dev_compiler
publish_to: "http://pub.dart-polymer.com"


dependencies:
  analyzer: ^0.30.0-alpha.3
  #analyzer: ^0.29.2
  args: ^0.13.0
  bazel_worker: ^0.1.0
  browser: ^0.10.0
  cli_util: ^0.0.1
  func: ^0.1.0
  html: ">=0.13.0 <1.14.0"
  js: ^0.6.0
  meta: ^1.0.3
  path: ^1.3.0
  pub_semver: ^1.1.0
  source_maps: ^0.10.0
  source_span: ^1.0.2

dev_dependencies:
  # We pin a specific version to ensure everyone is formatting the code exactly
  # the same way. This is because any change in dart_style, even non-breaking
  # changes, may change the output format.
#  dart_style: 0.2.4
#  test: 0.12.15+12
#  unittest: ^0.12.0
#  webdriver: any # ^1.1.0

dependency_overrides:
  # Depend directly on packages in the same repositiory
#  analyzer: { path: ../analyzer }
#  meta: { path: ../meta }

environment:
  sdk: ">=1.12.0 <2.0.0"
